import { jest } from '@jest/globals';

// Mock modules before imports
const mockCore = {
  getInput: jest.fn(),
  setFailed: jest.fn(),
  setOutput: jest.fn(),
  info: jest.fn(),
  warning: jest.fn()
};

const mockExec = {
  exec: jest.fn()
};

const mockGithub = {
  context: {
    payload: {
      repository: {
        private: false
      }
    },
    repo: {
      owner: 'testowner',
      repo: 'testrepo'
    }
  }
};

const mockOpenAI = {
  chat: {
    completions: {
      create: jest.fn()
    }
  }
};

jest.unstable_mockModule('@actions/core', () => mockCore);
jest.unstable_mockModule('@actions/exec', () => mockExec);
jest.unstable_mockModule('@actions/github', () => mockGithub);
jest.unstable_mockModule('openai', () => ({
  default: jest.fn(() => mockOpenAI)
}));

// Import after mocking
const {
  calculateRiskScore,
  getEmoji,
  generateFragileMd,
  parseLcovCoverage,
  validateLicense,
  getAIExplanation,
  getChangeFrequency,
  getReferenceCount,
  getAllSourceFiles,
  checkShallowClone,
  run
} = await import('../src/index.js');

describe('Fragile Action', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockCore.getInput.mockImplementation((name) => {
      const inputs = {
        'openai_key': 'test-key',
        'license_key': '',
        'top_n': '10',
        'min_references': '3',
        'coverage_path': ''
      };
      return inputs[name] || '';
    });
    mockGithub.context.payload.repository.private = false;
  });

  describe('calculateRiskScore', () => {
    test('calculates correct risk score with all parameters', () => {
      const score = calculateRiskScore(10, 20, 50);
      // (10 * 0.4) + (20 * 0.4) + (50 * 0.2) = 4 + 8 + 10 = 22
      expect(score).toBe(22);
    });

    test('calculates risk score with null coverage (defaults to 50% gap)', () => {
      const score = calculateRiskScore(10, 20, null);
      // (10 * 0.4) + (20 * 0.4) + (50 * 0.2) = 4 + 8 + 10 = 22
      expect(score).toBe(22);
    });

    test('calculates risk score with zero coverage (100% gap)', () => {
      const score = calculateRiskScore(10, 20, 0);
      // (10 * 0.4) + (20 * 0.4) + (100 * 0.2) = 4 + 8 + 20 = 32
      expect(score).toBe(32);
    });

    test('calculates risk score with full coverage (0% gap)', () => {
      const score = calculateRiskScore(10, 20, 100);
      // (10 * 0.4) + (20 * 0.4) + (0 * 0.2) = 4 + 8 + 0 = 12
      expect(score).toBe(12);
    });

    test('handles zero changes and references', () => {
      const score = calculateRiskScore(0, 0, 50);
      expect(score).toBe(10);
    });
  });

  describe('getEmoji', () => {
    test('returns red emoji for score >= 80', () => {
      expect(getEmoji(80)).toBe('🔴');
      expect(getEmoji(100)).toBe('🔴');
      expect(getEmoji(95)).toBe('🔴');
    });

    test('returns orange emoji for score 60-79', () => {
      expect(getEmoji(60)).toBe('🟠');
      expect(getEmoji(79)).toBe('🟠');
      expect(getEmoji(70)).toBe('🟠');
    });

    test('returns yellow emoji for score < 60', () => {
      expect(getEmoji(59)).toBe('🟡');
      expect(getEmoji(0)).toBe('🟡');
      expect(getEmoji(30)).toBe('🟡');
    });
  });

  describe('generateFragileMd', () => {
    test('generates correct format with files', () => {
      const files = [{
        path: 'src/index.js',
        score: 85,
        referenceCount: 15,
        changeCount: 20,
        coveragePct: 30,
        explanation: 'This is a critical file.'
      }];
      const md = generateFragileMd(files, '2024-01-15');

      expect(md).toContain('# FRAGILE.md');
      expect(md).toContain('Generated by [Fragile](https://fragile.dev)');
      expect(md).toContain('2024-01-15');
      expect(md).toContain('🔴 src/index.js');
      expect(md).toContain('**Risk score: 85**');
      expect(md).toContain('15 dependents');
      expect(md).toContain('changed 20 times in 90 days');
      expect(md).toContain('30% test coverage');
      expect(md).toContain('This is a critical file.');
    });

    test('generates no-findings message when no files', () => {
      const md = generateFragileMd([], '2024-01-15');
      expect(md).toContain('No fragile files detected');
    });

    test('shows N/A for null coverage', () => {
      const files = [{
        path: 'src/utils.js',
        score: 50,
        referenceCount: 5,
        changeCount: 10,
        coveragePct: null,
        explanation: 'Utility file.'
      }];
      const md = generateFragileMd(files, '2024-01-15');
      expect(md).toContain('N/A test coverage');
    });
  });

  describe('parseLcovCoverage', () => {
    test('returns null for empty path', () => {
      expect(parseLcovCoverage('')).toBeNull();
    });

    test('returns null for non-existent file', () => {
      expect(parseLcovCoverage('/nonexistent/path.info')).toBeNull();
    });

    test('rejects paths outside working directory', () => {
      // Attempting to read /etc/passwd or similar should be rejected
      const result = parseLcovCoverage('/etc/passwd');
      // Either returns null (file doesn't exist) or warns about path traversal
      expect(result).toBeNull();
    });
  });

  describe('License validation', () => {
    test('public repo skips license validation entirely', async () => {
      mockGithub.context.payload.repository.private = false;
      mockExec.exec.mockResolvedValue(0);
      mockOpenAI.chat.completions.create.mockResolvedValue({
        choices: [{ message: { content: 'Test explanation' } }]
      });

      const fetchSpy = jest.spyOn(global, 'fetch');

      await run();

      expect(fetchSpy).not.toHaveBeenCalledWith(
        'https://api.difflog.io/validate-fragile',
        expect.anything()
      );
    });

    test('private repo calls validate-fragile endpoint', async () => {
      mockGithub.context.payload.repository.private = true;
      mockCore.getInput.mockImplementation((name) => {
        if (name === 'openai_key') return 'test-key';
        if (name === 'license_key') return 'test-license';
        if (name === 'top_n') return '10';
        if (name === 'min_references') return '3';
        return '';
      });

      global.fetch = jest.fn().mockResolvedValue({
        json: () => Promise.resolve({ valid: true })
      });
      mockExec.exec.mockResolvedValue(0);
      mockOpenAI.chat.completions.create.mockResolvedValue({
        choices: [{ message: { content: 'Test explanation' } }]
      });

      await run();

      expect(global.fetch).toHaveBeenCalledWith(
        'https://api.difflog.io/validate-fragile',
        expect.objectContaining({
          method: 'POST',
          body: expect.stringContaining('test-license')
        })
      );
    });

    test('network timeout on license check fails open (continues)', async () => {
      global.fetch = jest.fn().mockRejectedValue(new Error('AbortError: timeout'));

      const result = await validateLicense('key', 'user', 'repo');
      expect(result.valid).toBe(true);
      expect(result.error).toBe(true);
    });

    test('invalid license key warns and exits 0', async () => {
      mockGithub.context.payload.repository.private = true;
      const mockExit = jest.spyOn(process, 'exit').mockImplementation(() => {});

      global.fetch = jest.fn().mockResolvedValue({
        json: () => Promise.resolve({ valid: false })
      });

      await run();

      expect(mockCore.warning).toHaveBeenCalledWith(
        'Invalid Fragile license key. Get one at fragile.dev'
      );
      expect(mockExit).toHaveBeenCalledWith(0);

      mockExit.mockRestore();
    });

    test('valid license key continues to analysis', async () => {
      mockGithub.context.payload.repository.private = true;

      global.fetch = jest.fn().mockResolvedValue({
        json: () => Promise.resolve({ valid: true })
      });
      mockExec.exec.mockResolvedValue(0);
      mockOpenAI.chat.completions.create.mockResolvedValue({
        choices: [{ message: { content: 'Test explanation' } }]
      });

      await run();

      expect(mockCore.info).toHaveBeenCalledWith('Analyzing repository for fragile files...');
    });
  });

  describe('min_references filter', () => {
    test('filters out low-reference files', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('ls-files')) {
          options?.listeners?.stdout?.(Buffer.from('src/index.js\nsrc/utils.js\n'));
        } else if (args && args.includes('--name-only')) {
          options?.listeners?.stdout?.(Buffer.from('src/index.js\n'));
        } else if (args && args[0] === 'grep') {
          options?.listeners?.stdout?.(Buffer.from(''));
        }
        return Promise.resolve(0);
      });

      mockOpenAI.chat.completions.create.mockResolvedValue({
        choices: [{ message: { content: 'Test explanation' } }]
      });

      await run();

      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining('Found'));
    });
  });

  describe('top_n limit', () => {
    test('limits output to N files', () => {
      const files = Array.from({ length: 20 }, (_, i) => ({
        path: `file${i}.js`,
        score: 100 - i,
        referenceCount: 10,
        changeCount: 5,
        coveragePct: 50,
        explanation: 'Test'
      }));

      const topFiles = files.slice(0, 10);
      expect(topFiles.length).toBe(10);
      expect(topFiles[0].score).toBe(100);
      expect(topFiles[9].score).toBe(91);
    });

    test('top_n=0 produces no output', async () => {
      mockCore.getInput.mockImplementation((name) => {
        if (name === 'openai_key') return 'test-key';
        if (name === 'top_n') return '0';
        return '';
      });

      await run();

      expect(mockCore.info).toHaveBeenCalledWith('top_n is 0, skipping analysis');
    });
  });

  describe('OpenAI API', () => {
    test('handles API error gracefully with placeholder explanation', async () => {
      const openai = {
        chat: {
          completions: {
            create: jest.fn().mockRejectedValue(new Error('API Error'))
          }
        }
      };

      const explanation = await getAIExplanation(openai, 'test.js', 5, 10, 50);

      expect(explanation).toContain('Unable to generate explanation');
      expect(mockCore.warning).toHaveBeenCalled();
    });

    test('handles empty choices array gracefully', async () => {
      const openai = {
        chat: {
          completions: {
            create: jest.fn().mockResolvedValue({ choices: [] })
          }
        }
      };

      const explanation = await getAIExplanation(openai, 'test.js', 5, 10, 50);

      expect(explanation).toContain('Unable to generate explanation');
      expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining('empty response'));
    });

    test('handles null content gracefully', async () => {
      const openai = {
        chat: {
          completions: {
            create: jest.fn().mockResolvedValue({
              choices: [{ message: { content: null } }]
            })
          }
        }
      };

      const explanation = await getAIExplanation(openai, 'test.js', 5, 10, 50);

      expect(explanation).toContain('Unable to generate explanation');
    });
  });

  describe('git log parsing', () => {
    test('handles files with spaces in name', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('--name-only')) {
          options?.listeners?.stdout?.(Buffer.from('src/my file.js\nsrc/other file.js\n'));
        }
        return Promise.resolve(0);
      });

      const result = await getChangeFrequency();
      expect(result['src/my file.js']).toBe(1);
      expect(result['src/other file.js']).toBe(1);
    });

    test('handles unicode paths', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('--name-only')) {
          options?.listeners?.stdout?.(Buffer.from('src/文件.js\nsrc/αρχείο.js\n'));
        }
        return Promise.resolve(0);
      });

      const result = await getChangeFrequency();
      expect(result['src/文件.js']).toBe(1);
      expect(result['src/αρχείο.js']).toBe(1);
    });
  });

  describe('reference counting', () => {
    test('parses grep results correctly', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args[0] === 'grep') {
          options?.listeners?.stdout?.(Buffer.from('src/a.js\nsrc/b.ts\nsrc/c.py\n'));
        }
        return Promise.resolve(0);
      });

      const count = await getReferenceCount('src/target.js');
      expect(count).toBe(3);
    });

    test('escapes regex special characters in filenames', async () => {
      let capturedPattern = null;
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args[0] === 'grep') {
          capturedPattern = args[3]; // The regex pattern argument
          options?.listeners?.stdout?.(Buffer.from(''));
        }
        return Promise.resolve(0);
      });

      await getReferenceCount('src/foo+bar[1].js');

      // The pattern should have escaped + and [ and ]
      expect(capturedPattern).toContain('foo\\+bar\\[1\\]');
    });
  });

  describe('coverage handling', () => {
    test('coverage_path missing shows as N/A', () => {
      const files = [{
        path: 'test.js',
        score: 50,
        referenceCount: 5,
        changeCount: 3,
        coveragePct: null,
        explanation: 'Test'
      }];

      const md = generateFragileMd(files, '2024-01-01');
      expect(md).toContain('N/A test coverage');
    });
  });

  describe('edge cases', () => {
    test('very large repo returns only top N', () => {
      const files = Array.from({ length: 1000 }, (_, i) => ({
        path: `file${i}.js`,
        score: Math.random() * 100
      }));

      files.sort((a, b) => b.score - a.score);
      const top10 = files.slice(0, 10);

      expect(top10.length).toBe(10);
      expect(top10[0].score).toBeGreaterThanOrEqual(top10[9].score);
    });

    test('files with zero changes in 90 days excluded unless high reference count', () => {
      const files = [
        { path: 'a.js', changeCount: 0, referenceCount: 2 },
        { path: 'b.js', changeCount: 0, referenceCount: 5 },
        { path: 'c.js', changeCount: 5, referenceCount: 5 }
      ];

      const minReferences = 3;
      const filtered = files.filter(f => f.referenceCount >= minReferences);

      expect(filtered.length).toBe(2);
      expect(filtered.find(f => f.path === 'a.js')).toBeUndefined();
    });
  });

  describe('FRAGILE.md commit', () => {
    test('commits FRAGILE.md to repo via git add/commit/push', async () => {
      mockExec.exec.mockImplementation((cmd, args) => {
        if (args && args.includes('diff')) {
          return Promise.reject(new Error('has changes'));
        }
        return Promise.resolve(0);
      });
      mockOpenAI.chat.completions.create.mockResolvedValue({
        choices: [{ message: { content: 'Test explanation' } }]
      });

      await run();

      expect(mockExec.exec).toHaveBeenCalledWith('git', ['add', 'FRAGILE.md']);
      expect(mockExec.exec).toHaveBeenCalledWith('git', ['commit', '-m', 'chore: update FRAGILE.md']);
      expect(mockExec.exec).toHaveBeenCalledWith('git', ['push']);
    });
  });

  describe('missing required inputs', () => {
    test('missing openai_key fails the action', async () => {
      mockCore.getInput.mockImplementation((name) => {
        if (name === 'openai_key') return '';
        return '';
      });

      await run();

      expect(mockCore.setFailed).toHaveBeenCalledWith('openai_key is required');
    });
  });

  describe('getAllSourceFiles', () => {
    test('returns list of source files', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('ls-files')) {
          options?.listeners?.stdout?.(Buffer.from('src/index.js\nlib/utils.ts\napp.py\n'));
        }
        return Promise.resolve(0);
      });

      const files = await getAllSourceFiles();
      expect(files).toContain('src/index.js');
      expect(files).toContain('lib/utils.ts');
      expect(files).toContain('app.py');
    });
  });

  describe('checkShallowClone', () => {
    test('warns when shallow clone detected with few commits', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('--count')) {
          options?.listeners?.stdout?.(Buffer.from('1\n'));
        } else if (args && args.includes('--is-shallow-repository')) {
          options?.listeners?.stdout?.(Buffer.from('true\n'));
        }
        return Promise.resolve(0);
      });

      await checkShallowClone();

      expect(mockCore.warning).toHaveBeenCalledWith(
        expect.stringContaining('fetch-depth')
      );
    });

    test('does not warn for full clone', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('--count')) {
          options?.listeners?.stdout?.(Buffer.from('100\n'));
        } else if (args && args.includes('--is-shallow-repository')) {
          options?.listeners?.stdout?.(Buffer.from('false\n'));
        }
        return Promise.resolve(0);
      });

      await checkShallowClone();

      expect(mockCore.warning).not.toHaveBeenCalledWith(
        expect.stringContaining('fetch-depth')
      );
    });
  });

  describe('OpenAI timeout handling', () => {
    test('returns specific timeout message on TIMEOUT error', async () => {
      const timeoutOpenAI = {
        chat: {
          completions: {
            create: jest.fn().mockRejectedValue(new Error('TIMEOUT'))
          }
        }
      };

      const explanation = await getAIExplanation(timeoutOpenAI, 'test.js', 5, 10, 50);

      expect(explanation).toContain('timed out');
      expect(explanation).toContain('OpenAI API key');
    });

    test('returns generic error message for non-timeout errors', async () => {
      const errorOpenAI = {
        chat: {
          completions: {
            create: jest.fn().mockRejectedValue(new Error('Rate limit exceeded'))
          }
        }
      };

      const explanation = await getAIExplanation(errorOpenAI, 'test.js', 5, 10, 50);

      expect(explanation).toContain('Unable to generate explanation');
      expect(explanation).not.toContain('timed out');
    });
  });

  describe('min_references edge cases', () => {
    test('min_references=0 is treated as 1', async () => {
      mockCore.getInput.mockImplementation((name) => {
        if (name === 'openai_key') return 'test-key';
        if (name === 'min_references') return '0';
        if (name === 'top_n') return '10';
        return '';
      });

      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('ls-files')) {
          options?.listeners?.stdout?.(Buffer.from('src/index.js\n'));
        } else if (args && args[0] === 'grep') {
          // Return 1 reference to test min_references=1 behavior
          options?.listeners?.stdout?.(Buffer.from('src/other.js\n'));
        } else if (args && args.includes('--is-shallow-repository')) {
          options?.listeners?.stdout?.(Buffer.from('false\n'));
        } else if (args && args.includes('--count')) {
          options?.listeners?.stdout?.(Buffer.from('100\n'));
        } else if (args && args.includes('diff')) {
          return Promise.resolve(0); // No changes
        }
        return Promise.resolve(0);
      });

      mockOpenAI.chat.completions.create.mockResolvedValue({
        choices: [{ message: { content: 'Test explanation' } }]
      });

      await run();

      // Should not fail - min_references of 0 treated as 1
      expect(mockCore.setFailed).not.toHaveBeenCalled();
    });

    test('negative min_references is treated as 1', async () => {
      mockCore.getInput.mockImplementation((name) => {
        if (name === 'openai_key') return 'test-key';
        if (name === 'min_references') return '-5';
        if (name === 'top_n') return '10';
        return '';
      });

      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args.includes('ls-files')) {
          options?.listeners?.stdout?.(Buffer.from(''));
        } else if (args && args.includes('--is-shallow-repository')) {
          options?.listeners?.stdout?.(Buffer.from('false\n'));
        } else if (args && args.includes('--count')) {
          options?.listeners?.stdout?.(Buffer.from('100\n'));
        } else if (args && args.includes('diff')) {
          return Promise.resolve(0);
        }
        return Promise.resolve(0);
      });

      await run();

      expect(mockCore.setFailed).not.toHaveBeenCalled();
    });
  });

  describe('multi-language reference counting', () => {
    test('counts Python imports', async () => {
      let capturedPattern = null;
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args[0] === 'grep') {
          capturedPattern = args[3];
          options?.listeners?.stdout?.(Buffer.from('app.py\nutils.py\n'));
        }
        return Promise.resolve(0);
      });

      const count = await getReferenceCount('src/module.py');

      expect(capturedPattern).toContain('from');
      expect(capturedPattern).toContain('import');
      expect(count).toBe(2);
    });

    test('counts Ruby requires', async () => {
      let capturedPattern = null;
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args[0] === 'grep') {
          capturedPattern = args[3];
          options?.listeners?.stdout?.(Buffer.from('app.rb\n'));
        }
        return Promise.resolve(0);
      });

      const count = await getReferenceCount('lib/helper.rb');

      expect(capturedPattern).toContain('require_relative');
      expect(count).toBe(1);
    });

    test('counts Go imports', async () => {
      mockExec.exec.mockImplementation((cmd, args, options) => {
        if (args && args[0] === 'grep') {
          options?.listeners?.stdout?.(Buffer.from('main.go\nhandler.go\n'));
        }
        return Promise.resolve(0);
      });

      const count = await getReferenceCount('pkg/utils.go');

      expect(count).toBe(2);
    });
  });
});
